version: '3'
services:
  openresty:
    build: ./openresty
    ports:
      - "8090:80"
      - "8091:81"
    links:
      - memcache:memcache
      - api:api
    environment:
      AUTH_API_URL: "http://api:8080"
  api:
    build: ./php
  memcache:
    image: "memcached:latest"
